In [7]:
import numpy as np
import pandas as pd
import pylab as pl
import matplotlib.pyplot as plt
plt.style.use('ggplot')
%matplotlib inline
import seaborn as sns


from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [32]:
df=pd.read_csv("C:/Users/User/Desktop/dataframe/dataset/ORGANICS.csv",encoding="cp1251")
print(df.shape) 
print(df.info())

(22223, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22223 entries, 0 to 22222
Data columns (total 13 columns):
ID                 22223 non-null int64
DemAffl            21138 non-null float64
DemAge             20715 non-null float64
DemCluster         21549 non-null float64
DemClusterGroup    21549 non-null object
DemGender          19711 non-null object
DemReg             21758 non-null object
DemTVReg           21758 non-null object
PromClass          22223 non-null object
PromSpend          22223 non-null float64
PromTime           21942 non-null float64
TargetBuy          22223 non-null int64
TargetAmt          22223 non-null int64
dtypes: float64(5), int64(3), object(5)
memory usage: 2.2+ MB
None

In [17]:

x=df[[c for c in df.columns if df[c].dtype.name != 'object' and c !="ID"and c !="TargetBuy" and c != "TargetAmt" ]]
df = df.fillna(df.median(axis=0), axis=0)
y=df.values[::,11]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

y_train = y_train.astype(int)
tree=DecisionTreeClassifier(max_depth=5, criterion = "entropy", random_state=0)
tree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [19]:
y_train = y_train.astype(int)
accuracy_score(y_train, tree.predict(X_train))

0.804705579840576

In [21]:
y_test = y_test.astype(int)
accuracy_score(y_test, tree.predict(X_test))

0.7966101694915254

In [57]:
#визуализация

from sklearn.tree import export_graphviz

import subprocess

export_graphviz(tree, out_file='C:/Users/User/Desktop/dataframe/Homework 3/Organics_tree.dot', 
               rounded = True, proportion = False, 
                precision = 2, filled = True)

import pydot 
(graph, ) = pydot.graph_from_dot_file('C:/Users/User/Desktop/dataframe/Homework 3/Organics_tree.dot')

#graph.write_png('Organics_tre.png')

In [22]:
df = df.fillna(df.median(axis=0), axis=0)
x=df[['DemAffl',  'DemAge', 'DemCluster', 'PromSpend', 'PromTime']]
y=df.values[::,11]

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

y_train = y_train.astype(int)
tree=DecisionTreeClassifier(max_depth=10, min_samples_leaf = 1, random_state=0)
tree.fit(X_train, y_train)

y_test = y_test.astype(int)
accuracy_score(y_test, tree.predict(X_test))

0.7931603419829009

In [23]:
df = df.fillna(df.median(axis=0), axis=0)
x=df[['DemAffl',  'DemAge', 'DemCluster', 'PromSpend', 'PromTime']]
y=df.values[::,11]

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

y_train = y_train.astype(int)
tree=DecisionTreeClassifier(max_depth=15, min_samples_leaf = 1, random_state=0)
tree.fit(X_train, y_train)

y_test = y_test.astype(int)
accuracy_score(y_test, tree.predict(X_test))

0.7474126293685316

In [24]:
df = df.fillna(df.median(axis=0), axis=0)
x=df[['DemAffl',  'DemAge', 'DemCluster', 'PromSpend', 'PromTime']]
y=df.values[::,11]

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

y_train = y_train.astype(int)
tree=DecisionTreeClassifier(max_depth=4, min_samples_leaf = 1, random_state=0)
tree.fit(X_train, y_train)

y_test = y_test.astype(int)
accuracy_score(y_test, tree.predict(X_test))

0.7967601619919004

In [25]:
df = df.fillna(df.median(axis=0), axis=0)
x=df[['DemAffl',  'DemAge', 'DemCluster', 'PromSpend', 'PromTime']]
y=df.values[::,11]

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

y_train = y_train.astype(int)
tree=DecisionTreeClassifier(max_depth=4, min_samples_leaf = 15, random_state=0)
tree.fit(X_train, y_train)

y_test = y_test.astype(int)
accuracy_score(y_test, tree.predict(X_test))

0.8048597570121494

In [68]:
df = df.fillna(df.median(axis=0), axis=0)
x=df[['DemAffl',  'DemAge', 'DemCluster', 'PromSpend', 'PromTime']]
y=df.values[::,11]

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

y_train = y_train.astype(int)
tree=DecisionTreeClassifier(max_depth=4, min_samples_leaf = 2, random_state=0)
tree.fit(X_train, y_train)

y_test = y_test.astype(int)
accuracy_score(y_test, tree.predict(X_test))

0.7931603419829009

Видим, что глубина вляет на точность. Чем больше глубина, тем ниже точность. min_samples_leaf существенно не влияет.

In [31]:
categorical_columns = [c for c in df.columns if  df[c].dtype.name == 'object']



def bin_coding(data, column_cat):
    for i in data[column_cat].unique(): #пробегаем по уникальным значениям кат переменной(поля, столбца)
        data[column_cat + "=" + i] = (data[column_cat] == i).astype(int) #кодируем
        
le = LabelEncoder()

for c in categorical_columns:
    
    df[c] = df[c].astype(str)
    le.fit(df[c])
    df[df[c].name +'Transform'] = le.fit_transform(df[c])
    bin_coding(df, c)
    
df

,ID,DemAffl,DemAge,DemCluster,DemClusterGroup,DemGender,DemReg,DemTVReg,PromClass,PromSpend,...,DemClusterGroupCheck,DemGenderCheck,DemRegCheck,DemTVRegCheck,PromClassCheck,DemClusterGroupTransform,DemGenderTransform,DemRegTransform,DemTVRegTransform,PromClassTransform
0,140,10.0,76.0,16.0,C,U,Midlands,Wales & West,Gold,16000.00,...,2,2,0,11,0,2,2,0,11,0
1,620,4.0,49.0,35.0,D,U,Midlands,Wales & West,Gold,6000.00,...,3,2,0,11,0,3,2,0,11,0
2,868,5.0,70.0,27.0,D,F,Midlands,Wales & West,Silver,0.02,...,3,0,0,11,2,3,0,0,11,2
3,1120,10.0,65.0,51.0,F,M,Midlands,Midlands,Tin,0.01,...,5,1,0,4,3,5,1,0,4,3
4,2313,11.0,68.0,4.0,A,F,Midlands,Midlands,Tin,0.01,...,0,0,0,4,3,0,0,0,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22218,52834058,13.0,65.0,9.0,B,F,South East,London,Silver,1500.00,...,1,0,3,3,2,1,0,3,3,2
22219,52834376,15.0,73.0,34.0,D,U,South East,S & S East,Gold,6053.06,...,3,2,3,8,0,3,2,3,8,0
22220,52837057,9.0,70.0,15.0,B,F,North,Yorkshire,Gold,6000.00,...,1,0,1,12,0,1,0,1,12,0
22221,52838096,11.0,66.0,8.0,B,F,North,N West,Silver,5000.00,...,1,0,1,7,2,1,0,1,7,2
22222,52856469,3.0,75.0,53.0,F,nan,South West,S West,Gold,6000.00,...,5,3,4,9,0,5,3,4,9,0